/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TblField.java
 *
 * Created on Aug 28, 2012, 4:59:46 PM
 */

package modules.id.ardi.view;

import java.util.ArrayList;
import java.util.List;
import modules.id.ardi.model.FieldModel;
import modules.id.ardi.model.TableFieldModel;

/**
 *
 * @author user
 */
public class TblField extends javax.swing.JDialog {
    
    /** Creates new form TblField */
    public TblField(List<FieldModel> list, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        listField = list;
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfm = new TableFieldModel(listField);
        jTbl_Field = new javax.swing.JTable();
        jB_Add = new javax.swing.JButton();
        jB_Del = new javax.swing.JButton();
        jB_Submit = new javax.swing.JButton();
        jLbl_TblField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTbl_Field.setModel(tfm);
        jScrollPane1.setViewportView(jTbl_Field);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jB_Add.setText("Add");
        jB_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AddActionPerformed(evt);
            }
        });

        jB_Del.setText("Del");
        jB_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DelActionPerformed(evt);
            }
        });

        jB_Submit.setText("Submit");
        jB_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SubmitActionPerformed(evt);
            }
        });

        jLbl_TblField.setText("Table Field ISO Server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jB_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLbl_TblField)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLbl_TblField)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Submit)
                    .addComponent(jB_Del)
                    .addComponent(jB_Add))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AddActionPerformed
        // TODO add your handling code here:
        tfm.addRow();
    }//GEN-LAST:event_jB_AddActionPerformed

    private void jB_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DelActionPerformed
        // TODO add your handling code here:
        tfm.removeRow();
    }//GEN-LAST:event_jB_DelActionPerformed

    private void jB_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SubmitActionPerformed
        // TODO add your handling code here:
        this.listField = tfm.getList();
        System.out.println("testing "+listField.get(listField.size()-1).getValue());
        this.setListField(tfm.getList());
        
        this.dispose();
        System.out.println("Submit action "+listField.size());
    }//GEN-LAST:event_jB_SubmitActionPerformed

    public List getListField(){
        return listField;
    }

    public void setListField(List lh){
        this.listField = lh;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Add;
    private javax.swing.JButton jB_Del;
    private javax.swing.JButton jB_Submit;
    private javax.swing.JLabel jLbl_TblField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    TableFieldModel tfm = null;
    private javax.swing.JTable jTbl_Field;
    // End of variables declaration//GEN-END:variables
    List<FieldModel> listField = new ArrayList<FieldModel>();
}
